### ISSUE TITLE
Notebooks fail with current utils version

### ISSUE THREAD

**Issue by supern8ent** [dream-olfaction/olfaction-prediction#8]
The third cell loading data fails in both challenge1.ipynb and challenge2.ipynb with the following error:

    1 # Load the perceptual descriptors data.
        ----> 2 perceptual_headers, perceptual_obs_data = loading.load_perceptual_data('training')
    3 loading.format_leaderboard_perceptual_data()
    4 # Show the perceptual metadata types and perceptual descriptor names.
    5 print(perceptual_headers)
    ValueError: too many values to unpack (expected 2)

I see that older commits have `utils.loading` that returns two objects, but those had other issues later in the code (something with fit1.py)

**Comment by rgerkin** [comment]
@supern8ent 
`challenge1.ipynb` and `challenge2.ipynb` reflect efforts made during the challenge, and will run with corresponding versions of the code, most likely any commit made between their last update and Feb. 23rd, 2017.  Feb 24th, 2017 saw a big change to the API which was used to produce the figures in the paper itself.  

If you are still interested in running `challenge1.ipynb` and `challenge2.ipynb`, though, let me know and I will update them to use the new API, perhaps with new names.  I hadn't done so before now because I wanted the cached output to reflect what was actually produced in the challenge rather than any improvements to the model(s) made since that time.

**Comment by supern8ent** [comment]
@rgerkin 
I think I should have been more clear previously: I actually did try a couple older commits, including one from dec 2015, and those were raising some exception in `fit1.py` (details below). I am definitely interested in running `challenge1.ipynb` etc., but if you can just point me to a working commit, that would suffice.

Error in Dec 2015 commit:

    # Fit training data.  Ignoring warning that arises if too few trees are used.  
    rfcs_leaderboard,score,rs = fit1.rfc_final(X_training,Y_training['subject'],
                            max_features,min_samples_leaf,max_depth,et,
                            n_estimators=n_estimators)
    KeyError                                  Traceback (most recent call last)
    <ipython-input-23-deed6f293fbb> in <module>()
          2 rfcs_leaderboard,score,rs = fit1.rfc_final(X_training,Y_training['subject'],
          3                             max_features,min_samples_leaf,max_depth,et,
    ----> 4                             n_estimators=n_estimators)
    
    .../opc_python/gerkin/fit1.py in rfc_final(X, Y, max_features, min_samples_leaf, max_depth, use_et, regularize, Y_test, n_estimators, seed)
         30         for subject in range(1,50):
         31             rfcs[col][subject] = rfc_maker(n_estimators=n_estimators,
    ---> 32                                 max_features=max_features[col],
         33                                 min_samples_leaf=min_samples_leaf[col],
         34                                 max_depth=max_depth[col],

    KeyError: 0

**Comment by rgerkin** [comment]
@supern8ent How about I change that notebook to reflect the current API.  Then it will technically not be the same code used in the challenge, but it should give approximately the same outcome.  Will that be OK with you?

**Comment by supern8ent** [comment]
@rgerkin That would be great!

**Comment by rgerkin** [comment]
@supern8ent 
OK, I'm on it.

**Comment by rgerkin** [comment]
@supern8ent 
In the dev branch I now have `challenge2.ipynb` working.  If you have any trouble you might want to run things from a Docker container like jupyter/scipy-notebook (I tested it in that one).  I'll fix `challenge1.ipynb` next.  For now these fixes are going to stay in the dev branch because I haven't checked to see if I introduced any bugs into the other notebooks that are focused on the findings in the paper, and keeping those intact is a higher priority.  So check out the dev branch and let me know if you have any problems with `challenge2.ipynb`.

**Comment by supern8ent** [comment]
@rgerkin 
Hi again, and thanks for working on this! I checked out dev branch and tried `challenge2.ipynb`, and it failed looking for a file named `LeaderboardSet.txt` in the data folder. I tried pointing it at `leaderboard_set.txt`, `LBs1.txt` and `LBs2.txt` (by editing line 23 of `loading.py`), and those all seem to be the wrong format:

    loading.py in load_perceptual_data(kind, just_headers, raw)
         43                             for x in line[6:]]
         44                 line[0] = CID = int(line[0])
    ---> 45                 dilution = line[4]
         46                 mag = dilution2magnitude(dilution)
         47                 CID_dilution = (CID,mag)
    IndexError: list index out of range

**Comment by rgerkin** [comment]
@supern8ent 
Sorry about that; I've added it to the `data` directory where it belongs.  Let me know if you notice anything else that is missing.  This is still all in the `dev` branch for now.

**Comment by supern8ent** [comment]
@rgerkin 
Challenge2.ipynb runs now. Thank you!
